version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: bimmi:backend_v1.0
    container_name: bimmi-backend
    hostname: backend
    restart: always
    ports:
      - 80:80
      - 443:443
